### ISSUE TITLE
 Cannot extract archives if path contains spaces

### ISSUE THREAD

**Issue by raphaelcastaneda** [Fantomas42/easy-extract#1]
To reproduce:

```python
test_directory = "C:\\some path with spaces"
my_finder = ArchiveFinder(test_directory, recursive=True, archive_classes=[RarArchive, ])
my_finder.extract()
```

Result:
```
Cannot open C:\some\.rar
Cannot find the path specified.
```

It appears that the command to launch the binary needs quotes around the archive path.

**Comment by Fantomas42** [comment]
Hello,

does this issue only appears on windows ?

I don't understand why escaped spaces don't do the trick...

Regards

**Comment by raphaelcastaneda** [comment]
Yes, this was on Windows, with python 2.7.10.

**Comment by Fantomas42** [comment]
I close this issue, because actually I cannot do testing.
Conclusion, Windows is not supported for the moment.
